import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#16222A',
  },
  container: {
    flex: 1,
    backgroundColor: '#16222A',
  },
  map: {
    flex: 1,
  },
  searchBar: {
    position: 'absolute',
    top: 12,
    left: 8,
    right: 8,
    height: 56,
    backgroundColor: '#0F2B3A',
    borderRadius: 24,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 20,
  },
  searchAvatar: {
    width: 50,
    height: 50,
    borderRadius: 20,
    marginRight: 10,
    overflow: 'hidden',
  },
  searchIcon: {
    marginLeft: 8,
    padding: 6,
  },
  searchInput: {
    flex: 1,
    color: '#FFF',
    paddingLeft: 8,
  },
  suggestionsContainer: {
    position: 'absolute',
    top: 64,
    left: 16,
    right: 16,
    backgroundColor: '#0F2B3A',
    borderRadius: 8,
    zIndex: 21,
    maxHeight: 200,
    paddingVertical: 6,
  },
  suggestionItem: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderBottomColor: 'rgba(255,255,255,0.03)',
    borderBottomWidth: 1,
  },
  suggestionText: {
    color: '#E6F3FF',
    fontSize: 14,
  },
  dateBubble: {
    position: 'absolute',
    top: 70,
    left: 16,
    backgroundColor: '#3B5566',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    zIndex: 20,
  },
  addressBubble: {
    position: 'absolute',
    top: 14,
    left: 64,
    right: 64,
    backgroundColor: 'rgba(0,0,0,0.5)',
    padding: 8,
    borderRadius: 10,
    alignItems: 'center',
    zIndex: 19,
  },
  bottomContainer: {
    backgroundColor: '#1E2A38',
    paddingVertical: 20,
    paddingHorizontal: 16,
    alignItems: 'center',
    width: '100%',
  },
  cityName: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 5,
    textAlign: 'center',
    width: '90%',
    alignSelf: 'center',
  },
  tempText: {
    color: '#E0E0E0',
    fontSize: 16,
  },
  coordsText: {
    color: '#CFE9FF',
    fontSize: 12,
    marginTop: 8,
    textAlign: 'center',
    width: '90%',
    alignSelf: 'center',
  },
  button: {
    backgroundColor: '#4A90E2',
    borderRadius: 10,
    padding: 12,
    marginTop: 10,
    width: '90%',
    maxWidth: 420,
    alignSelf: 'center',
    alignItems: 'center',
  },
  buttonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
});
